### ISSUE TITLE
Please provide materials remaining weeks too!

### ISSUE THREAD

**Issue by shakeabi** [NAU-ACM/ACM-ICPC-Preparation#16]

**Comment by BedirT** [comment]
Hi 👋 

**Sorry for inconvenience**, but due to my graduate school applications I am not and was not able to contribute as much, I summoned help from friends and reddit recently, I still will be active inspecting, but the speed is all up to the help I will receive from community. If not I can finish everything by February 2019, after my applications.

**Comment by shakeabi** [comment]
Thank you for replying. You've got a great resource there. Thank you so
much for compiling and making it open.
Great work!!

Abishake.

**Comment by rajat123456** [comment]
@shakeabi , most of the contents will be available before ICPC 2018, and complete set will be available by the end of this year :)

**Comment by shakeabi** [comment]
Please provide materials for all the weeks. It's a great compilation but would be better if it's complete.

**Comment by dipu-bd** [comment]
> Please provide materials for all the weeks. It's a great compilation but would be better if it's complete.

agree

**Comment by royayon** [comment]
I can't find anything after Week 13...? Can anyone help me?

**Comment by shakeabi** [comment]
@rajat123456 @BedirT Bump

**Comment by BedirT** [comment]
Duplicate of #4
